const STATS = [
  { value: '1', label: 'exe — no install required' },
  { value: '~20MB', label: 'application footprint' },
  { value: 'kHz', label: 'native Rust acquisition' },
  { value: '∞', label: 'runtimes — any CLI tool' },
]

const PILLARS = [
  {
    title: 'Data Acquisition Engine',
    body: 'Native Rust backend reads ADS variables at high speed. Multi-channel logging with millisecond-precision timestamps. Persistent to structured CSV with user-defined headers.',
    accent: 'teal' as const,
  },
  {
    title: 'Scripting IDE',
    body: 'Monaco editor, any runtime, one Play button. Python, Lua, Node, Perl, PowerShell, compiled executables — if it\'s in PATH it runs. Multiple scripts execute concurrently in independent terminal panels.',
    accent: 'blue' as const,
  },
  {
    title: 'Organised Workspace',
    body: 'GoldenLayout dockable panels. Project state saves and restores completely — every panel, position, size, and tab recovered on next open. Engineering workflows composable and persistent across sessions.',
    accent: 'amber' as const,
  },
]

const CURRENT_FEATURES = [
  {
    num: '00',
    title: 'Project Workspace Management',
    sub: 'Persistent engineering environments that save and restore complete workspace state',
    items: [
      'GoldenLayout panel configuration saves with every project — every panel, position, size, and tab restored on next open',
      'Project folder structure created automatically: Config/, Test Scripts/, Outputdata/, Calibrations/, Notes/',
      'Connection profiles, variable pins, script history, and user preferences persist per project',
      'Multiple projects supported — switch between machine setups without reconfiguring',
    ],
  },
  {
    num: '01',
    title: 'Full-Featured File Explorer',
    sub: 'Project-aware solution explorer with direct editor integration',
    items: [
      'Custom icons for .py, .lua, .js, .dacvar, .csv, calibration, and configuration file types',
      'Double-click any file to open directly in the Monaco editor',
      'Right-click context menus for common file operations',
      'Script output files (CSV, reports) appear in Outputdata/ immediately after generation',
    ],
  },
  {
    num: '02',
    title: 'Multi-Language Script Editor & Execution',
    sub: 'Monaco IDE with automatic runtime detection and one-click execution',
    items: [
      'Monaco editor — the same engine powering VS Code — with full syntax highlighting and IntelliSense',
      'Automatic runtime detection from file extension — .py, .lua, .js, .pl, .r, .jl, .ps1, .sh, .exe and more',
      'One Play button — resolves the correct launcher, opens a dedicated terminal panel, runs the script',
      'Multiple scripts execute concurrently in independent terminal panels',
      'Python for orchestration and analysis · Lua for performance-critical acquisition loops',
    ],
  },
  {
    num: '03',
    title: 'Integrated Terminal Panels',
    sub: 'Full command-line access piped directly into the workspace',
    items: [
      'Dedicated terminal panels piped into the workspace via PTY',
      'AI coding agents run natively: Claude Code, Cursor, Codex, and any CLI-based AI tool',
      'Multiple terminals open simultaneously — one per script, one per AI agent, one for shell work',
      'AI agents operate with full awareness of the project folder: scripts, logs, config, variable lists, calibration files',
      'Python package management from within the IDE — pip install without leaving the workspace',
    ],
  },
  {
    num: '04',
    title: 'Embedded Panel Views',
    sub: 'Web-based engineering tools and HMIs integrated directly into the workspace',
    items: [
      'Any web-based interface embeds as a first-class docked panel within DAC-ECAT Studio',
      'TwinCAT HMI panels display inside the workspace — machine control alongside data acquisition',
      'Streamlit and Plotly Dash dashboards generated by AI launch with one click and embed automatically',
      'Eliminates the fragmented multi-browser-window problem common in TwinCAT HMI deployments',
    ],
  },
  {
    num: '05',
    title: 'Centralised Logging System',
    sub: 'Unified event and diagnostic log across all active workspace panels',
    items: [
      'Single central logging panel aggregates output from all panels running within DAC-ECAT',
      'Captures events from script execution, ADS connections, variable changes, system messages',
      'Filterable by type: INFO, WARNING, ERROR, DEBUG, ADS, SCRIPT, SYSTEM',
      'Persistent log history within session — scroll back through the full session timeline',
    ],
  },
  {
    num: '06',
    title: 'Network Variable Explorer',
    sub: 'High-performance native Rust variable acquisition with full scope and logging integration',
    items: [
      'Connects to any AMS Net ID and port — local or remote — with route and firewall access',
      'Full PLC symbol tree with live values, type badges, and real-time updates',
      'DAC-ECAT structured types auto-enumerated on scan — alarm limits and warning bands render automatically',
      'Record button on any variable starts logging immediately to a timestamped CSV in Outputdata/',
      'User-defined custom headers for log files · Variable pin and filter workflows',
      'Right-click selected signals to open dedicated multi-variable scope windows',
    ],
  },
  {
    num: '07',
    title: 'AI-Assisted Engineering Workflows',
    sub: 'Full project context enabling AI agents to generate production-ready engineering tooling',
    items: [
      'AI agents have read access to the complete project: scripts, Outputdata/, Config/, Calibrations/, variable lists, and connection info',
      'AI generates complete runnable data logging scripts with correct symbol names, types, and ADS connection config pre-filled',
      'FFT analysis, signal processing, PID tuning, and statistical analysis scripts generated on demand',
      'Plotly and Streamlit dashboard generation — AI builds full interactive control and monitoring panels from the variable list',
      'Automated report generation — AI reads logged data and produces structured PDF or HTML reports',
    ],
  },
  {
    num: '08',
    title: 'DAC-ECAT PLC & HMI Libraries',
    sub: 'Professional TwinCAT PLC and HMI component libraries enabling structured machine control',
    items: [
      'DAC-ECAT PLC Library (TwinCAT 3): structured types, FB_StateMachine with method override pattern, FB_Queue with save/restore context',
      'Ping-pong buffer for high-speed data logging without cyclic ADS poll overhead',
      'DAC-ECAT HMI Library (TwinCAT HMI): one symbol binding per axis or channel instead of mapping individual variables',
      'DAC-ECAT types are optional — the variable explorer reads all ADS-exposed data without any library changes',
      'Virtual axis mode — state-driven simulated and real hardware modes without relinking drives',
    ],
  },
]

const PLANNED_FEATURES = [
  {
    id: 'P1',
    title: 'Notification System',
    sub: 'Automated event detection and programmable response functions',
    items: [
      'Alarm and warning threshold triggers defined from DAC-ECAT type metadata',
      'Configurable response functions: email, SMS, webhook, Slack, Teams notification on trigger',
      'Automatic logging start/stop driven by trigger events — capture only the data that matters',
    ],
  },
  {
    id: 'P2',
    title: 'Script Variable Inspector',
    sub: 'Post-execution script state inspection for rapid debugging',
    items: [
      'Inspector panel displays all script variables with type, value, shape, and size — similar to MATLAB workspace and Jupyter variable inspector',
      'Arrays and DataFrames expandable inline or as tabular view',
      'Persistent across script runs within a session — compare before and after state',
    ],
  },
  {
    id: 'P3',
    title: 'Expanded Protocol Support',
    sub: 'Mixed-protocol variable lists connecting to virtually any industrial device',
    items: [
      'EtherCAT SOEM — direct EtherCAT master connectivity without TwinCAT runtime',
      'Modbus TCP — drives, sensors, and controllers outside the Beckhoff ecosystem',
      'OPC UA — cross-vendor PLC connectivity (Siemens, Rockwell, B&R, and others)',
      'PROFINET and EtherNet/IP for broad industrial network coverage',
      'A single variable explorer panel with mixed connections to multiple PLCs from different vendors',
    ],
  },
  {
    id: 'P4',
    title: 'Cross-Platform Support',
    sub: 'Linux and macOS deployment using TCP/IP ADS connectivity',
    items: [
      'TwinCAT ADS communicates over TCP/IP and UDP — not a Windows-only protocol',
      'Tauri and Rust are inherently cross-platform — Linux and macOS builds are architecturally straightforward',
      'Linux build targets industrial PC deployments and embedded engineering workstations',
      'macOS build targets engineering teams on Apple hardware connecting to Windows TwinCAT PLCs',
    ],
  },
  {
    id: 'P5',
    title: 'Digital Twin Integration',
    sub: 'Live machine state connected to simulation and virtual representation environments',
    items: [
      'BaSyx Asset Administration Shell (AAS) integration for Industry 4.0 digital twin workflows',
      'Three.js visualization generation — AI writes machine geometry and animation scripts from variable data',
      'Simulation environment connectivity — test sequences against virtual hardware before physical commissioning',
    ],
  },
  {
    id: 'P6',
    title: 'Scripting Convenience Templates',
    sub: 'Right-click engineering blocks reducing repetitive boilerplate to zero',
    items: [
      'Right-click any variable to generate a complete, runnable script template',
      'Templates pre-fill: ADS connection config, symbol name, correct pyads data type, file output path',
      'Common patterns: single variable logger, multi-channel logger, FFT analyser, Streamlit dashboard, PID step test, alarm monitor',
      'Template library expandable by engineers — save custom patterns to the project for team reuse',
    ],
  },
  {
    id: 'P7',
    title: 'Built-In Security Tools',
    sub: 'UUID generation and passphrase hashing built directly into the application — no internet connection required',
    items: [
      'UUID Generator: cryptographically random RFC 4122 v4 UUID for project identity — generated locally, never transmitted',
      'Hash Generator: SHA-256 digest of a facility passphrase for write-access security in TwinCAT GVL',
      'Read/Write security model: all ADS reads always permitted; write access is session-locked via passphrase hash comparison',
      'Plaintext passphrase never stored anywhere — not in the PLC, not in DAC-ECAT, not transmitted over the network',
    ],
  },
]

const ROADMAP_COLUMNS = [
  {
    label: 'Shipping Now',
    accent: 'teal' as const,
    items: [
      'TwinCAT ADS · Windows',
      'Project workspace management',
      'Solution explorer',
      'Monaco multi-language IDE',
      'Open runtime execution',
      'Terminal panel integration',
      'Embedded panel views',
      'Central logging system',
      'Native Rust variable explorer',
      'In-panel and scope plotting',
      'Record and CSV logging',
      'AI terminal integration',
      'DAC-ECAT PLC library',
      'DAC-ECAT HMI controls',
    ],
  },
  {
    label: 'Near Term',
    accent: 'blue' as const,
    items: [
      'Notification and trigger system',
      'Script variable inspector',
      'EtherCAT SOEM',
      'Modbus TCP',
      'OPC UA',
      'PROFINET · EtherNet/IP',
      'Scripting convenience templates',
      'Built-in security tools (UUID + hash)',
      'Linux · macOS builds',
      'Digital twin (BaSyx AAS)',
      'Report generation (PDF/HTML)',
      'Git integration',
    ],
  },
  {
    label: 'Long Term',
    accent: 'amber' as const,
    items: [
      'Universal industrial workspace',
      'Mixed-vendor variable lists',
      'Cross-protocol interoperability',
      'Industrial analytics platform',
      'AI-assisted machine engineering',
      'Predictive maintenance tooling',
      'Collaborative engineering workflows',
      'Industry-specific vertical products',
      'Cloud-connected diagnostics',
      'Simulation environment integration',
    ],
  },
]

const ACCENT_STYLE = {
  teal: { label: 'text-brand-teal', border: 'border-brand-teal/25', dot: 'bg-brand-teal/50', head: 'bg-brand-teal/10' },
  blue: { label: 'text-brand-blue', border: 'border-brand-blue/25', dot: 'bg-brand-blue/50', head: 'bg-brand-blue/10' },
  amber: { label: 'text-brand-amber', border: 'border-brand-amber/25', dot: 'bg-brand-amber/50', head: 'bg-brand-amber/10' },
}

export default function ProductOverview() {
  return (
    <div className="pt-28 pb-0">

      {/* ── Header ── */}
      <section className="px-6 pb-16 text-center relative">
        <div className="absolute inset-0 bg-hero-radial" />
        <div className="relative max-w-3xl mx-auto">
          <p className="font-mono text-xs tracking-[0.3em] text-brand-teal uppercase mb-4">
            — Product Overview —
          </p>
          <h1 className="font-orbitron font-bold text-4xl md:text-5xl tracking-wider text-brand-bright uppercase mb-5">
            What is DAC-ECAT Studio?
          </h1>
          <p className="font-mono text-brand-text text-sm leading-relaxed max-w-2xl mx-auto mb-6">
            A data acquisition and logging engine integrated development environment for industrial
            automation engineers. Connect to TwinCAT PLCs, acquire live data at native speeds, script
            in any language, visualize signals, and generate engineering tooling with AI assistance —
            all inside one unified native desktop application.
          </p>
          <blockquote className="font-mono text-brand-teal/80 text-xs italic tracking-wider">
            Any industrial device should become observable, scriptable, and extensible from one unified workspace.
          </blockquote>
        </div>
      </section>

      {/* ── Stats bar ── */}
      <section className="px-6 pb-16">
        <div className="max-w-3xl mx-auto">
          <div className="rounded-xl border border-brand-border bg-brand-surface shadow-panel">
            <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-y md:divide-y-0 divide-brand-border">
              {STATS.map(({ value, label }) => (
                <div key={label} className="p-6 text-center">
                  <p className="font-orbitron font-black text-3xl text-brand-teal mb-1">{value}</p>
                  <p className="font-mono text-[11px] text-brand-dim tracking-wider uppercase leading-snug">{label}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ── Three Pillars ── */}
      <section className="px-6 pb-24 relative">
        <div className="absolute inset-0 bg-feature-radial" />
        <div className="relative max-w-6xl mx-auto">
          <div className="text-center mb-12">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-teal uppercase mb-4">— Architecture —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase">
              Three Pillars, One Application
            </h2>
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {PILLARS.map((p) => {
              const s = ACCENT_STYLE[p.accent]
              return (
                <div key={p.title} className={`rounded-xl border bg-brand-surface p-6 shadow-panel ${s.border}`}>
                  <h3 className={`font-orbitron font-bold text-xs tracking-wider uppercase mb-3 ${s.label}`}>{p.title}</h3>
                  <p className="font-mono text-brand-text text-xs leading-relaxed">{p.body}</p>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* ── Platform Support ── */}
      <section className="px-6 pb-24 border-t border-brand-border">
        <div className="max-w-4xl mx-auto pt-24">
          <div className="text-center mb-12">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-teal uppercase mb-4">— Platform —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase">
              Current & Roadmap Support
            </h2>
          </div>
          <div className="grid md:grid-cols-2 gap-5">
            <div className="rounded-xl border border-brand-teal/25 bg-brand-surface p-6 shadow-panel">
              <p className="font-orbitron font-bold text-xs tracking-wider text-brand-teal uppercase mb-4">Shipping Now</p>
              <ul className="space-y-2">
                {['TwinCAT ADS — local and remote', 'Windows — all modern versions', 'Beckhoff AMS Net ID routing'].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-brand-teal mt-1.5 flex-shrink-0" />
                    <span className="font-mono text-xs text-brand-bright">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="rounded-xl border border-brand-border bg-brand-surface p-6 shadow-panel">
              <p className="font-orbitron font-bold text-xs tracking-wider text-brand-dim uppercase mb-4">Planned Roadmap</p>
              <ul className="space-y-2">
                {['EtherCAT SOEM', 'Modbus TCP', 'OPC UA', 'PROFINET · EtherNet/IP', 'Linux · macOS (via TCP/IP ADS)', 'Mixed protocol variable lists'].map((item) => (
                  <li key={item} className="flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-brand-border mt-1.5 flex-shrink-0" />
                    <span className="font-mono text-xs text-brand-text">{item}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
          <p className="font-mono text-brand-dim text-xs mt-4 text-center leading-relaxed">
            TwinCAT ADS communicates over TCP/IP and UDP — once Linux and macOS builds are available, DAC-ECAT Studio connects to Windows-based TwinCAT PLCs from any platform. The Tauri and Rust architecture is cross-platform by design.
          </p>
        </div>
      </section>

      {/* ── Current Features ── */}
      <section className="px-6 pb-24 border-t border-brand-border">
        <div className="max-w-5xl mx-auto pt-24">
          <div className="text-center mb-16">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-teal uppercase mb-4">— Shipping Now —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase mb-4">
              Current Features
            </h2>
            <p className="font-mono text-brand-text text-xs">
              All features below are implemented and shipping in the current release for Windows with TwinCAT ADS connectivity.
            </p>
          </div>
          <div className="space-y-4">
            {CURRENT_FEATURES.map((f) => (
              <div key={f.num} className="rounded-lg border border-brand-border bg-brand-surface shadow-panel overflow-hidden">
                <div className="flex items-start gap-4 p-5">
                  <span className="font-orbitron font-black text-2xl text-brand-teal/20 leading-none flex-shrink-0 mt-0.5 select-none w-8">
                    {f.num}
                  </span>
                  <div className="flex-1 min-w-0">
                    <h3 className="font-orbitron font-bold text-sm tracking-wider text-brand-bright uppercase mb-1">{f.title}</h3>
                    <p className="font-mono text-[11px] text-brand-teal/70 italic mb-3">{f.sub}</p>
                    <ul className="space-y-1.5">
                      {f.items.map((item, i) => (
                        <li key={i} className="flex items-start gap-2">
                          <span className="w-1 h-1 rounded-full bg-brand-teal/40 mt-1.5 flex-shrink-0" />
                          <span className="font-mono text-[11px] text-brand-text leading-relaxed">{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Planned Features ── */}
      <section className="px-6 pb-24 border-t border-brand-border">
        <div className="max-w-5xl mx-auto pt-24">
          <div className="text-center mb-16">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-blue uppercase mb-4">— Roadmap —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase mb-4">
              Planned Features
            </h2>
            <p className="font-mono text-brand-text text-xs">
              The following capabilities are in active development or on the near-term roadmap.
            </p>
          </div>
          <div className="grid md:grid-cols-2 gap-4">
            {PLANNED_FEATURES.map((f) => (
              <div key={f.id} className="rounded-lg border border-brand-border bg-brand-surface shadow-panel p-5">
                <div className="flex items-start gap-3 mb-3">
                  <span className="font-orbitron font-black text-xs text-brand-blue/50 flex-shrink-0 mt-0.5">{f.id}</span>
                  <div>
                    <h3 className="font-orbitron font-bold text-xs tracking-wider text-brand-blue uppercase mb-0.5">{f.title}</h3>
                    <p className="font-mono text-[10px] text-brand-dim italic">{f.sub}</p>
                  </div>
                </div>
                <ul className="space-y-1.5 pl-6">
                  {f.items.map((item, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="w-1 h-1 rounded-full bg-brand-blue/40 mt-1.5 flex-shrink-0" />
                      <span className="font-mono text-[11px] text-brand-text leading-relaxed">{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Technical Architecture ── */}
      <section className="px-6 pb-24 border-t border-brand-border">
        <div className="max-w-5xl mx-auto pt-24">
          <div className="text-center mb-16">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-teal uppercase mb-4">— Under the Hood —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase">
              Technical Architecture
            </h2>
          </div>
          <div className="grid md:grid-cols-3 gap-5 mb-8">
            {[
              { title: 'Native Performance', body: 'Rust backend handles ADS acquisition, file I/O, and terminal management without JavaScript overhead in the critical data path.', accent: 'teal' as const },
              { title: 'Memory Safety', body: "Rust's ownership model eliminates memory safety vulnerabilities at compile time — important for software interacting with live industrial hardware.", accent: 'teal' as const },
              { title: '~20MB Single Exe', body: 'No installer. No runtime dependency. No admin rights. Copy to any Windows machine and run. No IT involvement required.', accent: 'teal' as const },
            ].map((item) => {
              const s = ACCENT_STYLE[item.accent]
              return (
                <div key={item.title} className={`rounded-xl border bg-brand-surface p-5 shadow-panel ${s.border}`}>
                  <h3 className={`font-orbitron font-bold text-xs tracking-wider uppercase mb-2 ${s.label}`}>{item.title}</h3>
                  <p className="font-mono text-brand-text text-xs leading-relaxed">{item.body}</p>
                </div>
              )
            })}
          </div>
          <div className="rounded-xl border border-brand-teal/15 bg-brand-teal/5 p-6 mb-8">
            <p className="font-mono text-brand-text text-xs leading-relaxed italic">
              Governments and major technology organisations worldwide — including agencies within the United States government — have publicly advocated for memory-safe languages in critical infrastructure software. DAC-ECAT Studio is built on exactly that foundation.
            </p>
          </div>
          <div className="rounded-xl border border-brand-border bg-brand-surface shadow-panel overflow-hidden">
            <div className="px-5 py-4 border-b border-brand-border bg-brand-bg/50">
              <p className="font-orbitron font-bold text-xs tracking-wider text-brand-bright uppercase">Script Engine — Open Runtime Architecture</p>
            </div>
            <div className="grid md:grid-cols-3 divide-y md:divide-y-0 divide-x divide-brand-border">
              {[
                {
                  lang: 'Python', tag: 'primary', accent: 'teal' as const,
                  items: ['NumPy, pandas, SciPy', 'matplotlib, Plotly, Streamlit', 'pyads, pyserial, pymodbus', 'TensorFlow, PyTorch, OpenCV', 'Thousands of scientific libraries'],
                },
                {
                  lang: 'Lua / LuaJIT', tag: 'performance', accent: 'blue' as const,
                  items: ['Near-native execution speed', 'Tight acquisition loops at speed', 'Parallel to Python via PLC flags', 'No GIL — true concurrent execution', 'Minimal CPU and memory overhead'],
                },
                {
                  lang: 'Any Runtime', tag: 'open', accent: 'amber' as const,
                  items: ['Node.js (.js) · Perl (.pl)', 'PowerShell (.ps1)', 'R (.r) · Julia (.jl)', 'Shell scripts (.sh)', 'Compiled executables (.exe)', 'Any CLI-accessible tool'],
                },
              ].map((col) => {
                const s = ACCENT_STYLE[col.accent]
                return (
                  <div key={col.lang} className="p-5">
                    <p className={`font-orbitron font-bold text-xs tracking-wider uppercase mb-0.5 ${s.label}`}>{col.lang}</p>
                    <p className="font-mono text-[10px] text-brand-dim italic mb-3">{col.tag}</p>
                    <ul className="space-y-1.5">
                      {col.items.map((item) => (
                        <li key={item} className="flex items-start gap-1.5">
                          <span className={`w-1 h-1 rounded-full mt-1.5 flex-shrink-0 ${s.dot}`} />
                          <span className="font-mono text-[10px] text-brand-text">{item}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )
              })}
            </div>
            <div className="px-5 py-3 border-t border-brand-border bg-brand-bg/30">
              <p className="font-mono text-[10px] text-brand-dim italic">
                The PLC is the coordination layer. Python orchestrates test sequences and sets flags. Lua watches flags and logs at maximum speed. Any number of scripts participate simultaneously — they coordinate through PLC variables visible in the explorer.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ── Platform Philosophy ── */}
      <section className="px-6 pb-24 border-t border-brand-border">
        <div className="max-w-5xl mx-auto pt-24">
          <div className="text-center mb-12">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-teal uppercase mb-4">— Philosophy —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase mb-3">
              Open Integration — No Lock-In
            </h2>
            <p className="font-mono text-brand-text text-xs max-w-xl mx-auto">
              DAC-ECAT Studio connects to existing TwinCAT systems without requiring changes to PLC projects or architectures. Engineers adopt incrementally.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-5 mb-8">
            {[
              { title: 'Standard ADS Variables', accent: 'dim' as const, body: 'Connect to any ADS-accessible PLC. Browse and log any symbol. Full variable explorer and scope functionality. No library changes required.' },
              { title: 'DAC-ECAT Types', accent: 'teal' as const, body: 'Drop DacEcat_LReal into any PLC struct. DAC-ECAT auto-discovers it. Alarm lines, warning bands, and target lines render automatically.' },
              { title: 'Full Framework', accent: 'amber' as const, body: 'Use the DacEcat PLC and HMI libraries for the complete architecture: state machines, queues, HMI controls, and health monitoring.' },
            ].map((col) => {
              const accent = col.accent === 'dim' ? 'border-brand-border text-brand-dim' : col.accent === 'teal' ? 'border-brand-teal/30 text-brand-teal' : 'border-brand-amber/30 text-brand-amber'
              return (
                <div key={col.title} className={`rounded-xl border bg-brand-surface p-6 shadow-panel ${accent.split(' ')[0]}`}>
                  <h3 className={`font-orbitron font-bold text-xs tracking-wider uppercase mb-3 ${accent.split(' ')[1]}`}>{col.title}</h3>
                  <p className="font-mono text-brand-text text-xs leading-relaxed">{col.body}</p>
                </div>
              )
            })}
          </div>
          <p className="font-mono text-brand-teal text-xs text-center italic tracking-wider">
            Progressive enhancement. Zero-friction adoption. No disruption to existing PLC projects.
          </p>
        </div>
      </section>

      {/* ── Competitive Differentiation ── */}
      <section className="px-6 pb-24 border-t border-brand-border">
        <div className="max-w-5xl mx-auto pt-24">
          <div className="text-center mb-16">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-teal uppercase mb-4">— Differentiation —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase">
              How DAC-ECAT Compares
            </h2>
          </div>
          {[
            {
              label: 'vs. Traditional TwinCAT Vendor Tooling',
              rows: [
                ['Configuration and runtime management focused', 'Engineering productivity and observability focused'],
                ['Fixed proprietary scripting environment or none', 'Any runtime — Python, Lua, Node, R, Julia, executables'],
                ['No integrated IDE or script editor', 'Full Monaco IDE with syntax highlighting and execution'],
                ['Requires installation, licensing, and IT involvement', 'Single 20MB exe — copy and run anywhere'],
                ['No AI integration', 'AI agents with full project context run natively'],
                ['Rigid fixed layouts', 'Fully dockable composable GoldenLayout workspace'],
                ['Disconnected logging and analysis tools', 'Acquisition, logging, scripting, and analysis in one application'],
              ],
            },
            {
              label: 'vs. Generic Industrial Data Loggers',
              rows: [
                ['Fixed rigid logging pipelines', 'Fully scriptable — any acquisition pattern in any language'],
                ['Disconnected from analysis and scripting', 'Logs feed directly into Python, MATLAB, R, or any analysis tool'],
                ['Protocol limited', 'TwinCAT ADS now — multi-protocol roadmap'],
                ['No scripting or extension capability', 'Full Monaco IDE with open runtime — any tool, any library'],
                ['No AI integration', 'AI generates logging scripts in seconds with correct symbol names pre-filled'],
                ['Manual file naming and organisation', 'Timestamped auto-named outputs in structured project folders'],
              ],
            },
            {
              label: 'vs. Generic AI Coding Tools',
              rows: [
                ['No industrial protocol awareness', 'Native TwinCAT ADS with Rust backend acquisition'],
                ['No PLC variable understanding', 'Full symbol tree with types and offsets as AI context'],
                ['No live runtime connectivity', 'AI agents run inside a live connected engineering session'],
                ['Generic code generation', 'Generates correct pyads, pymodbus, industrial library code'],
                ['No awareness of engineering data', 'AI reads logged CSVs, calibration files, and variable lists'],
                ['Operates in isolation', 'AI operates inside the live project folder with full file access'],
              ],
            },
          ].map((table) => (
            <div key={table.label} className="mb-10">
              <h3 className="font-orbitron font-bold text-xs tracking-wider text-brand-teal uppercase mb-4">{table.label}</h3>
              <div className="rounded-xl border border-brand-border bg-brand-surface overflow-hidden shadow-panel">
                <table className="w-full font-mono text-xs">
                  <thead>
                    <tr className="border-b border-brand-border">
                      <th className="text-left px-5 py-2.5 text-brand-dim tracking-wider uppercase w-1/2">Others</th>
                      <th className="text-left px-5 py-2.5 text-brand-teal tracking-wider uppercase w-1/2">DAC-ECAT Studio</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-brand-border">
                    {table.rows.map(([left, right], i) => (
                      <tr key={i} className="hover:bg-brand-surface-raised/30 transition-colors">
                        <td className="px-5 py-3 text-brand-dim">{left}</td>
                        <td className="px-5 py-3 text-brand-bright font-medium">{right}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Long-Term Roadmap ── */}
      <section className="px-6 pb-28 border-t border-brand-border">
        <div className="max-w-5xl mx-auto pt-24">
          <div className="text-center mb-16">
            <p className="font-mono text-xs tracking-[0.3em] text-brand-amber uppercase mb-4">— Vision —</p>
            <h2 className="font-orbitron font-bold text-2xl md:text-3xl tracking-wider text-brand-bright uppercase mb-4">
              Long-Term Roadmap
            </h2>
            <p className="font-mono text-brand-text text-xs max-w-2xl mx-auto leading-relaxed">
              DAC-ECAT Studio begins with TwinCAT ADS on Windows and expands systematically into cross-platform support and broader industrial protocol interoperability.
            </p>
          </div>
          <div className="grid md:grid-cols-3 gap-5 mb-10">
            {ROADMAP_COLUMNS.map((col) => {
              const s = ACCENT_STYLE[col.accent]
              return (
                <div key={col.label} className={`rounded-xl border bg-brand-surface shadow-panel overflow-hidden ${s.border}`}>
                  <div className={`px-5 py-3 border-b border-brand-border ${s.head}`}>
                    <p className={`font-orbitron font-bold text-xs tracking-wider uppercase ${s.label}`}>{col.label}</p>
                  </div>
                  <ul className="p-5 space-y-2">
                    {col.items.map((item) => (
                      <li key={item} className="flex items-start gap-2">
                        <span className={`w-1 h-1 rounded-full mt-1.5 flex-shrink-0 ${s.dot}`} />
                        <span className="font-mono text-[11px] text-brand-text leading-relaxed">{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )
            })}
          </div>
          <div className="rounded-xl border border-brand-teal/15 bg-brand-teal/5 p-6 text-center">
            <p className="font-mono text-brand-text text-xs leading-relaxed italic max-w-3xl mx-auto">
              DAC-ECAT Studio evolves from a TwinCAT data acquisition and scripting IDE into a universal industrial engineering workspace — supporting live data acquisition, programmable scripting, AI-assisted engineering, and cross-protocol industrial interoperability across every major platform and protocol.
            </p>
          </div>
        </div>
      </section>
    </div>
  )
}
